"""Create tables

Revision ID: c6e756c28d82
Revises: 
Create Date: 2025-02-23 10:33:23.939301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6e756c28d82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('klair_clips', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('klair_clips', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('klair_clips', 'start_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('klair_clips', 'end_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('klair_clips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_klair_clips_id'), 'klair_clips', ['id'], unique=False)
    op.alter_column('klair_videos', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('klair_videos', 'duration_seconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('klair_videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_klair_videos_id'), 'klair_videos', ['id'], unique=False)
    op.alter_column('raven_chats', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('raven_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_raven_chats_created_at', table_name='raven_chats')
    op.drop_index('idx_raven_chats_id', table_name='raven_chats')
    op.drop_index('idx_raven_chats_user_id', table_name='raven_chats')
    op.create_index(op.f('ix_raven_chats_id'), 'raven_chats', ['id'], unique=False)
    op.alter_column('raven_messages', 'chat_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('raven_messages', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('raven_messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_raven_messages_chat_id', table_name='raven_messages')
    op.drop_index('idx_raven_messages_timestamp', table_name='raven_messages')
    op.create_index(op.f('ix_raven_messages_id'), 'raven_messages', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_raven_messages_id'), table_name='raven_messages')
    op.create_index('idx_raven_messages_timestamp', 'raven_messages', ['timestamp'], unique=False)
    op.create_index('idx_raven_messages_chat_id', 'raven_messages', ['chat_id'], unique=False)
    op.alter_column('raven_messages', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('raven_messages', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('raven_messages', 'chat_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_raven_chats_id'), table_name='raven_chats')
    op.create_index('idx_raven_chats_user_id', 'raven_chats', ['user_id'], unique=False)
    op.create_index('idx_raven_chats_id', 'raven_chats', ['id'], unique=False)
    op.create_index('idx_raven_chats_created_at', 'raven_chats', ['created_at'], unique=False)
    op.alter_column('raven_chats', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('raven_chats', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_klair_videos_id'), table_name='klair_videos')
    op.alter_column('klair_videos', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('klair_videos', 'duration_seconds',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('klair_videos', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_klair_clips_id'), table_name='klair_clips')
    op.alter_column('klair_clips', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('klair_clips', 'end_time',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('klair_clips', 'start_time',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('klair_clips', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('klair_clips', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
